# Generated by Django 2.1.7 on 2020-07-23 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_register_student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2)),
                ('parent_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=14)),
                ('id_pic', models.ImageField(default='uploads/user-no-image.png', upload_to=main_register_student.models.photo_id, verbose_name='img')),
                ('profile_pic', models.ImageField(upload_to=main_register_student.models.photo_profile, verbose_name='img')),
                ('schedule_1', models.CharField(max_length=20)),
                ('schedule_2', models.CharField(max_length=20)),
                ('schedule_3', models.CharField(max_length=20)),
                ('schedule_4', models.CharField(max_length=20)),
                ('schedule_5', models.CharField(max_length=20)),
                ('schedule_6', models.CharField(max_length=20)),
                ('grade', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA')], default='', max_length=3)),
                ('total_student', models.CharField(max_length=250)),
                ('school', models.CharField(max_length=150)),
                ('mode', models.CharField(max_length=150)),
                ('user_type', models.CharField(default='student', editable=False, max_length=100)),
                ('status', models.BooleanField(default=False, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
