# Generated by Django 2.1.7 on 2020-07-23 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_absence_schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField(default=False)),
                ('absence_pic', models.ImageField(upload_to=main_absence_schedule.models.photo_prove, verbose_name='img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Absence',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('mode', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL)),
                ('user_tentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_absence_schedule.Schedule'),
        ),
    ]
