# Generated by Django 2.1.7 on 2020-08-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_register_tentor', '0001_initial'),
        ('main_register_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_student_absence', to='main_register_student.Students')),
                ('user_tentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tentor_absence', to='main_register_tentor.Tentors')),
                ('attend_student', models.BooleanField(default=False)),
                ('student_assign_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('attend_tentor', models.BooleanField(default=False)),
                ('tentor_assign_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('grade', models.CharField(choices=[('SD 1', 'SD 1'), ('SD 2', 'SD 2'), ('SD 3', 'SD 3'), ('SD 4', 'SD 4'), ('SD 5', 'SD 5'), ('SD 6', 'SD 6'), ('SMP 7', 'SMP 7'), ('SMP 8', 'SMP 8'), ('SMP 9', 'SMP 9'), ('SMA 10', 'SMA 10'), ('SMA 11', 'SMA 11'), ('SMA 12', 'SMA 12')], default='', max_length=10)),
                ('mode', models.CharField(choices=[('online (remote)', 'Online (remote)'), ('offline', 'Offline')], max_length=250)),
                ('total_student', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Absence',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=250)),
                ('mapel', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('mode', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to='main_register_student.Students')),
                ('user_tentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tentor', to='main_register_tentor.Tentors')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_absence_schedule.Schedule'),
        ),
    ]
