# Generated by Django 2.1.7 on 2020-07-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Tentors',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('account_name', models.CharField(max_length=250)),
                ('account_id', models.IntegerField()),
                ('university', models.CharField(max_length=150)),
                ('major', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='tentor', editable=False, max_length=100)),
                ('status', models.BooleanField(default=False, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_register_tentor.Bank')),
            ],
            options={
                'verbose_name_plural': 'Tentor',
            },
        ),
    ]
