# Generated by Django 2.1.7 on 2020-08-05 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_register_tentor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Tentors',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=250)),
                ('account_name', models.CharField(max_length=250)),
                ('account_id', models.CharField(max_length=20)),
                ('bank_other', models.CharField(default='', max_length=20)),
                ('university', models.CharField(max_length=150)),
                ('major', models.CharField(max_length=100)),
                ('number_id', models.CharField(max_length=100)),
                ('id_pic', models.ImageField(upload_to=main_register_tentor.models.photo_id, verbose_name='img')),
                ('profile_pic', models.ImageField(default='uploads/user-no-image.png', upload_to=main_register_tentor.models.photo_profile, verbose_name='img')),
                ('user_type', models.CharField(default='tentor', editable=False, max_length=100)),
                ('status', models.BooleanField(default=False, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_register_tentor.Bank')),
            ],
            options={
                'verbose_name_plural': 'Tentor',
            },
        ),
    ]
